language: node_js
node_js:
  - "4.1"
services:
  - mongodb
before_install:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - "mongo cobalt --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})'"
install:
  - npm install
script:
  - npm test
