language: node_js
node_js:
  - "4.1"
services:
  - mongodb
before_install:
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
install:
  - npm install
script:
  - npm test
