language: node_js
node_js:
  - "4.1"
services:
  - mongodb
install:
  - npm install
before_script:
  - "mongo cobalt --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
script:
  - npm test
